version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomation_AWSSTAGE02Project
  gitServerName: kusi_AWSStage02
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
